apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchcache-exporter 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: watchcache-exporter
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: watchcache-exporter 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watchcache-exporter
subjects:
- kind: ServiceAccount
  name: watchcache-exporter
  namespace: kube-system
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: watchcache-exporter
  labels:
    app: watchcache-exporter
spec:
  selector:
    matchLabels:
      app: watchcache-exporter
  template:
    metadata:
      labels:
        app: watchcache-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/target: "kubernetes"
    spec:
      containers:
      - name: watchcache-exporter
        image: sapcc/kubernetes-watchcache-exporter:latest
        imagePullPolicy: Always
      serviceAccountName: watchcache-exporter
